name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: cwaits6/.github/.github/workflows/release.yml@main
    with:
      go-binary-name: apk-index
      go-main-package: ./cmd/apk-index
      go-ldflags-prefix: github.com/cwaits6/apk-datasource/cmd/apk-index/cmd
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
