name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: cwaits6/.github/.github/workflows/release.yml@main
    with:
      go-binary-name: apk-index
      go-main-package: ./cmd/apk-index
      go-ldflags-prefix: github.com/cwaits6/apk-datasource/cmd/apk-index/cmd
