name: Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

permissions: read-all

jobs:
  scorecard:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: cwaits6/.github/.github/workflows/scorecard.yml@main
